Confirminput
Diren-T/capstone-project pull request #10
Opened 2023-02-14 14:23 UTC by Diren-T

2023-02-14 15:26 UTC, F-Kirchhoff commented on components/Navbar/index.js
> +  justify-sontent: space-evebly;
typos: "content", "evenly"

2023-02-14 15:27 UTC, F-Kirchhoff commented on components/Navbar/index.js
> +    <>
fragments not needed

2023-02-14 15:27 UTC, F-Kirchhoff commented on pages/_document.js
> +// import { ServerStyleSheet } from "styled-components";
remove code instead of commenting it out.

2023-02-14 15:28 UTC, F-Kirchhoff commented on pages/_document.js
> +//     const originalRenderPage = ctx.renderPage;
here too

2023-02-14 15:28 UTC, F-Kirchhoff commented on pages/_document.js
> +//         });
here too, and everywhere else where you did it.

2023-02-14 15:29 UTC, F-Kirchhoff commented on pages/dashboard.js
> +      <div>
this div is not needed

2023-02-14 15:34 UTC, F-Kirchhoff commented on pages/index.js
> +const key = "Bearer 1592SDMAYNMEM5HXCP8S7953NK93";
This is critical, please save your access tokens in a .env.local. You should fetch from an api Route, not from the client. Please send a get request from the client to an API endpoint (you can create it in /pages/api/trip). Then you fetch the requested data from climatiq in the handler function at that api endpoint. Because the api endpoints run in node.js and not in the browser, they can access the process.env object which contains the environment variables which you specify in the .env.local. Then you can send the data back to your client.

2023-02-14 15:40 UTC, F-Kirchhoff commented on pages/index.js
> +              />
Do you want to use the values of tripType / tripClass anywhere else than in this controlling of the inputs? If not, you don't need to control the inputs. Then you can delete the states related to these inputs and remove the checked and onChange props. as long as the radio inputs share the same name, the html handles this behavior for you.

2023-02-14 15:40 UTC, F-Kirchhoff commented on pages/index.js
> +              />
here as well

2023-02-14 15:41 UTC, F-Kirchhoff commented on pages/index.js
> +    </article>
instead of article you can use `<>` here.

2023-02-15 08:28 UTC, Diren-T commented on pages/index.js
> +const key = "Bearer 1592SDMAYNMEM5HXCP8S7953NK93";
good comment, i fixed it.

2023-02-15 10:16 UTC, NikRoe requested changes
Hi there,

left a few notes. Please implement the suggestions.

I noticed that you cannot fetch any data on your vercel deployment. 
You have to set the environment variable in Vercel (and give it the same value it has in your .env.local file): https://vercel.com/docs/concepts/projects/environment-variables

2023-02-15 10:16 UTC, NikRoe commented on components/Footer/index.js
> +export default Footer;
you don't need another component that only returns your styled component

(be aware that your imports need to be updated as well)

```suggestion
export StyledFooter;
```

2023-02-15 11:26 UTC, Diren-T commented on components/Card/Index.js
> +    <section>
i have change this

2023-02-15 11:26 UTC, Diren-T commented on package.json
> +    "install": "^0.13.0",
i don't know exactly what this is, i haven't installed it. would you recommend to delete this

2023-02-15 13:45 UTC, AGeck113 approved these changes

2023-02-15 13:45 UTC, AGeck113 commented on components/Navbar/index.js
> +  align-items: flex-end
Just the semicolon at the end
`align-items: flex-end;`

2023-02-15 13:45 UTC, AGeck113 commented on pages/flightCard.js
> +import React from "react";
Do you need React here?

2023-02-15 13:45 UTC, AGeck113 commented on pages/index.js
>  import React, { useState } from "react";
And do you need it here?

2023-02-15 15:56 UTC, merged