feature/flightinfo
Diren-T/capstone-project pull request #5
Opened 2023-01-30 10:52 UTC by Diren-T

Enter flights details in form

2023-01-30 11:07 UTC, doemser requested changes

2023-01-30 11:07 UTC, doemser commented on pages/index.js
> +
In this case I think it makes little sense to use controlled inputs. Rather use formData here. A good reason to use controlled inputs is if you want to prefill the form, which is not the case here.

2023-01-30 11:07 UTC, doemser commented on pages/index.js
> +          placeholder="IATA code"
Placeholders tend to be an a11y issue. Either the contrast is too low, or they are mistaken to be prefilled textContent. Consider not setting a placeholder.

2023-01-30 11:07 UTC, doemser commented on pages/index.js
> +        <br />
using <br/> to add a "new line" is kinda dirty. Can you think of another way to do that?

2023-01-31 13:00 UTC, TariqAlQadi reviewed
Looks good!
still wouldnt use className

2023-01-31 14:03 UTC, Diren-T commented on pages/index.js
> +      <form className="form" onSubmit={handleSubmit}>
thanks, i will change this :)

2023-01-31 14:04 UTC, merged